name: MultiWorld
main: multiworld.MultiWorldPlugin
version: 4.5.4
dev-url: http://dev.bukkit.org/server-mods/multiworld-v-2-0/
website: http://dev.bukkit.org/server-mods/multiworld-v-2-0/
author: ferrybig
description: >
             Provides multiworld support
commands:
   multiworld:
      description: 多世界插件指令帮助
      usage:
           /<command> <commandaction> <arg1> <arg2>
   mw:
      description: 所有指令
      usage:
           /<command> <commandaction> <arg1> <arg2>
   goto:
      description: 传送到一个世界
      usage:
           /<command> <world>
      permission: multiworld.command.goto
permissions:
    multiworld.*:
        description: 与 multiworld.admin 相同
        children:
            multiworld.admin: true
    multiworld.minium:
        description: 最常用的权限
        children:
            multiworld.command.goto: true
            multiworld.command.list: true
    multiworld.basic:
        description: 基本权限
        children:
            multiworld.minium: true
            multiworld.command.getflag: true
            multiworld.command.flaglist: true
            multiworld.command.help: true
            multiworld.command.info: true
            multiworld.creativemode: true
    multiworld.moderate:
        description: 巡查员权限
        children:
            multiworld.basic: true
            multiworld.command.setflag: true
            multiworld.command.save: true
            multiworld.command.reload: true
            multiworld.command.link: true
            multiworld.command.move: true
    multiworld.admin:
        description: 管理员权限
        children:
            multiworld.moderate: true
            multiworld.worldmaneger: true
            multiworld.command.debug: true
            multiworld.command.spawn: true
            multiworld.command.setspawn: true
            multiworld.command.listgens: true
    multiworld.worldmaneger:
        description: 世界管理者权限
        children:
            multiworld.command.world.create: true
            multiworld.command.world.unload: true
            multiworld.command.world.load: true
            multiworld.command.world.delete: true
            multiworld.command.list: true
    multiworld.command.goto:
        description: 传送到指定的世界
        default: op
    multiworld.command.list:
        description: 列出所有世界
        default: op
    multiworld.command.unload:
        description: 卸载世界
        default: op
    multiworld.command.load:
        description: 加载世界
        default: op
    multiworld.command.create:
        description: 创建一个世界
        default: op
    multiworld.command.delete:
        description: 删除一个世界
        default: op
    multiworld.command.save:
        description: 保存数据
        default: op
    multiworld.command.link:
        description: 链接世界的地狱/末地门传送到另一个世界
        children:
            multiworld.command.link.*: true
    multiworld.command.link.*:
        description: 链接世界的地狱/末地门传送到另一个世界
        children:
            multiworld.command.link.nether: true
            multiworld.command.link.end: true
    multiworld.command.link.nether:
        description: 链接世界的地狱门传送到另一个世界
        default: op
    multiworld.command.link.end:
        description: 链接世界的末地门传送到另一个世界
        default: op
    multiworld.command.reload:
        description: 重新加载插件
        default: op
    multiworld.command.help:
        description: 显示帮助文本
        default: op
    multiworld.command.setflag:
        description: 设置一个世界的选项
        default: op
    multiworld.command.getflag:
        description: 获取一世界的选项
        default: op
    multiworld.creativemode:
        description: 在创造模式的世界获取创造模式
        default: op
    multiworld.command.debug:
        description: 显示多世界插件调试信息
        default: op
    multiworld.command.move:
        description: 将一个玩家移动到另一个世界
        default: op
    multiworld.command.spawn:
        description: 传送到世界的出生点
        default: op
    multiworld.command.setspawn:
        description: 设置世界的出生点
        default: op
    multiworld.command.flaglist:
        description: 使用 /mw getflag 世界使用的标志
        default: op
    multiworld.command.listgens:
        description: 列出所有可用的世界生成器
        default: op
    multiworld.command.info:
        description: 列出世界的基本信息
        default: op